# @format

name: Build
run-name: Build

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]-*-*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Setup Rust
        uses: moonrepo/setup-rust@v1.2.2

      - name: Create cache of Android SDK
        id: android-cache
        uses: actions/cache@v4
        with:
          key: android-sdk-cache-36
          path: ${{ github.workspace }}/android-sdk

      - name: Setup Android SDK, NDK, Platform-tools
        if: steps.android-cache.outputs.cache-hit != true
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
        run: |
          mkdir -p $ANDROID_HOME/cmdline-tools
          curl -o cmdline-tools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
          unzip cmdline-tools.zip -d $ANDROID_HOME/cmdline-tools
          mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest

          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH

          yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_HOME \
            "platform-tools" \
            "platforms;android-36" \
            "ndk;25.2.9519653"

          echo "Installed SDK:"
          ls -l $ANDROID_HOME

      - name: Configure Android SDK for Gradle
        env:
          ANDROID_HOME: ${{ github.workspace }}/android-sdk
        run: |
          mkdir -p android-sdk
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
          echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        id: build_deb
        run: ./gradlew composeApp:packageDeb
        continue-on-error: true

      - name: Print jpackage logs
        if: steps.build_deb.outcome == 'failure'
        run: |
          echo "::group::jpackage Standard Output"
          cat composeApp/build/compose/logs/packageDeb/*-out.txt
          echo "::endgroup::"

          echo "::group::jpackage Error Log"
          cat composeApp/build/compose/logs/packageDeb/*-err.txt
          echo "::endgroup::"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: composeApp/build/compose/binaries/main/**.deb
